apiVersion: v1
kind: ConfigMap
metadata:
  name: kraken
data:
  {{- if .Values.agent.enabled }}
  agent.yaml: {{ tpl (.Files.Get "config/agent.yaml") . | toYaml | indent 2 }}
  {{- end }}
  {{- if .Values.build_index.enabled }}
  build-index.yaml: {{ tpl (.Files.Get "config/build-index.yaml") . | toYaml | indent 2 }}
  {{- end }}
  {{- if .Values.origin.enabled }}
  origin.yaml: {{ tpl (.Files.Get "config/origin.yaml") . | toYaml | indent 2 }}
  {{- end }}
  {{- if .Values.proxy.enabled }}
  proxy.yaml: {{ tpl (.Files.Get "config/proxy.yaml") . | toYaml | indent 2 }}
  {{- end }}
  {{- if .Values.tracker.enabled }}
  tracker.yaml: {{ tpl (.Files.Get "config/tracker.yaml") . | toYaml | indent 2 }}
  {{- end }}
{{- if and .Values.agent.enabled .Values.agent.secretConfig }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kraken-agent
data:
  secrets.yaml: {{ tpl .Values.agent.secretConfig . | toYaml | indent 2 | b64enc }}
{{- end }}
{{- if and .Values.build_index.enabled .Values.build_index.secretConfig }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kraken-build-index
data:
  secrets.yaml: {{ tpl .Values.build_index.secretConfig . | toYaml | indent 2 | b64enc }}
{{- end }}
{{- if and .Values.origin.enabled .Values.origin.secretConfig }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kraken-origin
data:
  secrets.yaml: {{ tpl .Values.origin.secretConfig . | toYaml | indent 2 | b64enc }}
{{- end }}
{{- if and .Values.proxy.enabled .Values.proxy.secretConfig }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kraken-proxy
data:
  secrets.yaml: {{ tpl .Values.proxy.secretConfig . | toYaml | indent 2 | b64enc }}
{{- end }}
{{- if and .Values.tracker.enabled .Values.tracker.secretConfig }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kraken-tracker
data:
  secrets.yaml: {{ tpl .Values.tracker.secretConfig . | toYaml | indent 2 | b64enc }}
{{- end }}