{{- if .Values.origin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraken-origin
spec:
  replicas: {{ .Values.origin.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kraken
      app.kubernetes.io/component: origin
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kraken
        app.kubernetes.io/component: origin
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{ with .Values.origin.annotations -}}
      annotations:
{{ tpl . $ | indent 8 }}
      {{- end }}
    spec:
      {{ with .Values.origin.tolerations -}}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{ with .Values.origin.affinity -}}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{ with .Values.origin.initContainers -}}
      initContainers:
{{ toYaml . | indent 6 }}{{ end }}
      containers:
      - name: main
        image: {{ .Values.kraken.repository }}/kraken-origin:{{ .Values.kraken.tag }}
        imagePullPolicy: {{ .Values.kraken.imagePullPolicy }}
        command:
        - /bin/bash
        - -c
        - "sleep 30 && /usr/bin/kraken-origin --config={{ .Values.origin.config }} --blobserver-port=80 --peer-port=8080 --cluster={{ .Values.kraken.cluster }} --zone={{ .Values.kraken.zone }}{{if .Values.origin.secretConfig}} --secrets=/etc/secrets/secrets.yaml{{end}}"
        volumeMounts:
        - name: config
          mountPath: /etc/config
        {{- if .Values.origin.secretConfig }}      
        - name: secret
          mountPath: /etc/secrets
        {{- end }}
        ports:
        - containerPort: 80
          name: blobserver
        - containerPort: 8080
          name: peer
        - containerPort: 9000
          name: metrics
{{ with .Values.origin.extraVolumeMounts }}{{ toYaml . | indent 8 }}{{ end }}
    {{- with .Values.kraken.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: config
        configMap:
          name: kraken
      {{- if .Values.origin.secretConfig }}      
      - name: secret
        secret:
          secretName: kraken-origin
      {{- end }}
{{ with .Values.origin.extraVolumes }}{{ toYaml . | indent 6 }}{{ end }}
---
kind: Service
apiVersion: v1
metadata:
  name: kraken-origin
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: kraken
    app.kubernetes.io/component: origin
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
{{- if .Values.kraken.disruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kraken-origin
  labels:
    app.kubernetes.io/name: kraken
    app.kubernetes.io/component: origin
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  minAvailable: {{ .Values.kraken.disruptionBudget.minAvaiable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kraken
      app.kubernetes.io/component: origin
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}