{{- if .Values.proxy.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraken-proxy
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kraken
      app.kubernetes.io/component: proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kraken
        app.kubernetes.io/component: proxy
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{ with .Values.proxy.annotations -}}
      annotations:
{{ tpl . $ | indent 8 }}
      {{- end }}
    spec:
      {{ with .Values.proxy.affinity -}}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{ with .Values.proxy.initContainers -}}
      initContainers:
{{ toYaml . | indent 6 }}{{ end }}
      containers:
      - name: main
        image: {{ .Values.kraken.repository }}/kraken-proxy:{{ .Values.kraken.tag }}
        imagePullPolicy: {{ .Values.kraken.imagePullPolicy }}
        command:
        - /usr/bin/kraken-proxy
        - --config={{ .Values.proxy.config }}
        - --port=80
        - --server-port=10050
        - --cluster={{ .Values.kraken.cluster }}
        {{- if .Values.proxy.secretConfig }}      
        - --secrets=/etc/secrets/secrets.yaml
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/config
        {{- if .Values.proxy.secretConfig }}      
        - name: secret
          mountPath: /etc/secrets
        {{- end }}
{{ with .Values.proxy.extraVolumeMounts }}{{ toYaml . | indent 8 }}{{ end }}
        ports:
        - containerPort: 80
          name: proxy
        - containerPort: 10050
          name: server-port
        - containerPort: 9000
          name: metrics
        livenessProbe:
          httpGet:
            path: /health
            port: server-port
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: server-port
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: server-port
          periodSeconds: 10
          initialDelaySeconds: 5
    {{- with .Values.kraken.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: config
        configMap:
          name: kraken
      {{- if .Values.proxy.secretConfig }}      
      - name: secret
        secret:
          secretName: kraken-proxy
      {{- end }}
{{ with .Values.proxy.extraVolumes }}{{ toYaml . | indent 6 }}{{ end }}
---
kind: Service
apiVersion: v1
metadata:
  name: kraken-proxy
spec:
  selector:
    app.kubernetes.io/name: kraken
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: proxy
  - protocol: TCP
    port: 10050
    targetPort: 10050
    name: server
{{- if .Values.kraken.disruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kraken-proxy
  labels:
    app.kubernetes.io/name: kraken
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  minAvailable: {{ .Values.kraken.disruptionBudget.minAvaiable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kraken
      app.kubernetes.io/component: proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}