{{- if .Values.tracker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraken-tracker
spec:
  replicas: {{ .Values.tracker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kraken
      app.kubernetes.io/component: tracker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kraken
        app.kubernetes.io/component: tracker
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{ with .Values.tracker.annotations -}}
      annotations:
{{ tpl . $ | indent 8 }}
      {{- end }}
    spec:
      {{ with .Values.tracker.affinity -}}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{ with .Values.tracker.initContainers -}}
      initContainers:
{{ tpl . $ | indent 6 }}{{- end }}
      containers:
      {{- if not .Values.tracker.externalRedis.enabled }}
      - name: redis
        image: redis:5.0
      {{- end }}
      - name: main
        image: {{ .Values.kraken.repository }}/kraken-tracker:{{ .Values.kraken.tag }}
        imagePullPolicy: {{ .Values.kraken.imagePullPolicy }}
        command:
        - /bin/bash
        - -c
        - "sleep 30 && /usr/bin/kraken-tracker --config={{ .Values.tracker.config }} --port=80 --cluster={{ .Values.kraken.cluster }}{{if .Values.tracker.secretConfig}} --secrets=/etc/secrets/secrets.yaml{{end}}"
        volumeMounts:
        - name: config
          mountPath: /etc/config
        {{- if .Values.tracker.secretConfig }}      
        - name: secret
          mountPath: /etc/secrets
        {{- end }}
        ports:
        - containerPort: 80
          name: tracker
    {{- with .Values.kraken.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{ with .Values.tracker.extraVolumeMounts }}{{ toYaml . | indent 8 }}{{ end }}
      volumes:
      - name: config
        configMap:
          name: kraken
      {{- if .Values.tracker.secretConfig }}      
      - name: secret
        secret:
          secretName: kraken-tracker
      {{- end }}
{{ with .Values.tracker.extraVolumes }}{{ toYaml . | indent 6 }}{{ end }}
---
kind: Service
apiVersion: v1
metadata:
  name: kraken-tracker
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: kraken
    app.kubernetes.io/component: tracker
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
{{- if .Values.kraken.disruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kraken-tracker
  labels:
    app.kubernetes.io/name: kraken
    app.kubernetes.io/component: tracker
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  minAvailable: {{ .Values.kraken.disruptionBudget.minAvaiable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kraken
      app.kubernetes.io/component: tracker
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}