FROM mcr.microsoft.com/windows/servercore:20H2

ARG NGINX_VERSION=1.21.6

# Setup folder structure as close to linux version as possible
RUN mkdir C:\nginx && \
    mkdir C:\usr\sbin && \
    mkdir C:\etc && \
    curl -o "%TMP%\nginx-%NGINX_VERSION%.zip" "http://nginx.org/download/nginx-%NGINX_VERSION%.zip" && \
    tar -xf "%TMP%\nginx-%NGINX_VERSION%.zip" -C C:\nginx && \
    xcopy "C:\nginx\nginx-%NGINX_VERSION%\conf" C:\etc\nginx /E /H /I && \
    del "%TMP%\nginx-%NGINX_VERSION%.zip"

ENV NGINX_BINARY=C:\\nginx\\nginx-$NGINX_VERSION\\nginx.exe

RUN mkdir C:\var\log\kraken\kraken-agent
RUN mkdir C:\var\cache\kraken\kraken-agent
RUN mkdir C:\var\run\kraken


COPY ./agent/agent.exe /usr/bin/kraken-agent
COPY ./config /etc/kraken/config
COPY ./nginx/config /etc/kraken/nginx/config
COPY ./test/tls /etc/kraken/tls

WORKDIR C:/etc/kraken
